Website/Website/urls.py
from django.contrib import admin
from django.urls import path , include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('myWebsite.urls'))
]

Website/myWebsite/urls.py
from django.urls import path
from . import views

app_name = "myWebsite"

urlpatterns = [

    path("about/", views.Abuot_me ,name = "about"),
    path("contact/", views.contact ,name = "contact")
]

Website/myWebsite/views.py
from django.shortcuts import render
from django.http import HttpRequest, HttpResponse

# Create your views here.
def Abuot_me(request: HttpRequest):
    my_self = ['']
    context = {'myself' : my_self}
    return render(request, 'myWebsite/about.html', context)

def contact(request: HttpRequest):
    concat_co = ['']
    context = {'con' : concat_co}
    return render(request, 'myWebsite/contact.html', context)

Website/myWebsite/templates/myWebsite/about.html
{% extends 'myWebsite/base.html' %}
{% block content %}

<h1>Bakhet Alrwes</h1>

        
 
      </section>
      

      <section class="about-me">
        <div id="about-me">
          <h2>About Me</h2>
          <p>My name's Bakhet ,
            I live in Riyadh , I'm 24 years old.
             </p>
        </div>
      </section>



{% endblock %}

Website/myWebsite/templates/myWebsite/base.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>{% block title %}

    {% endblock  %}
    <style>
        body {
  margin: -1.1rem 0;
}

.header {
  height: 40rem;
  background-image: url("https://ununsplash.imgix.net/46/iYvDeqVGRbebiQv2PIJi_DSC_8407.JPG?q=75&fm=jpg&s=a7538e1162bc4239180bb02813de4739");
  background-color: #b0c4de;
  background-position: center center;
  background-repeat: no-repeat;
}

.header h1 {
  color: white;
  font-family: "Lato";
  font-weight: 700;
  font-size: 10rem;
  margin: 0 0;
  padding: 13rem;
  text-align: center;
}

.header h3 {
  margin: -14rem 0;
  text-align: center;
  color: white;
  font-family: "Lato";
  font-weight: 300;
  font-size: 3rem;
}

.nav {
  height: 3rem;
  background-color: #85B0A6;
  text-align: center;  
  padding: 1rem 0 .6rem 0;
}

.nav ul li {
  display: inline;
  margin: 1.2rem;
}

.nav ul li a {
  font-family: "Lato";
  font-weight: 500;
  text-decoration: none;
  color: #3C3E4F;
}

.about-me {
  background-color: #3C3E4F;
  margin-top: -2rem;
  margin-bottom: -2rem;
}

#about-me {
  max-width: 63rem;
  margin: 0 auto;
}

.about-me h2 {
  font-family: "Lato";
  font-weight: 500;
  font-size: 2rem;
  padding-top: 4rem;
  color: white;
}

.about-me p {
  font-family: "Lato";
  font-weight: 300;
  font-size: 1.2rem;
  padding-bottom: 4rem;
  color: white;
}

.portfolio {
  margin-top: 2rem;
  background-color: #BDC49A
}

#portfolio {
  max-width: 63rem;
  margin: 0 auto;
  padding-bottom: 2rem;
}

.portfolio h2 {
  font-family: "Lato";
  font-weight: 500;
  font-size: 2rem;
  padding-top: 4rem;
  color: black; 
}

#unroll-box {
  height: 300px;
  width: 600px;
  background-image: url("https://f.cl.ly/items/1r1v1z3b1Y0q03250x1P/unroll-box1.png");
  background-repeat: no-repeat;
  border: .16rem solid #85B0A6;
}

.portfolio h3 {
  font-family: "Lato";
  font-weight: 300;
  font-size: 1.3rem;
  padding-top: .8rem;
  margin-top: 0;
  color: black;
  padding-bottom: 2rem;
  margin-bottom: 0;
}

#personal-box {
  height: 300px;
  width: 600px;
  background-image: url("https://f.cl.ly/items/051V2T0m1u2O3d0b0q0t/personal-box.png");
  background-repeat: no-repeat;
  border: .16rem solid #85B0A6;
}

.portfolio h3 {
  font-family: "Lato";
  font-weight: 300;
  font-size: 1.3rem;
  padding-top: .8rem;
  margin-top: 0;
  color: black;
  padding-bottom: 2rem;
  margin-bottom: 0;
}


    </style>


</head>
  <body>
    <section class="nav">
        <ul>
          <li><a href="{% url 'myWebsite:about'%}">About Me</a></li>
          <li><a href="{% url 'myWebsite:contact'%}">Contact</a></li>
        </ul>
      </section>
      

      <section class="header">
        {% block content %}
        <h1>Bakhet Alrwes</h1>

        
 
      </section>
      

      <section class="about-me">
        <div id="about-me">
          <h2>About Me</h2>
          <p>Hi </p>
        </div>
      </section>
      {% endblock %}
       
      
      <section class="contact">
      <div id="contact">
        
      </div>  
      </section>
  </body>
</html>

Website/myWebsite/templates/myWebsite/contact.html
{% extends 'myWebsite/base.html' %}
{% block content %}
    <h1 href="https://github.com/bakhet98">git hub  </h1>
{% endblock %}