MyDjango_website/Myself/Myself/urls.py
from django.contrib import admin
from django.urls import path, include



urlpatterns = [
    path('admin/', admin.site.urls),
    path('home/', include('mywebsite.urls')
)
]

MyDjango_website/Myself/mywebsite/urls.py
from django.urls import path
from . import views


app_name = "MyWebsite"
urlpatterns = [
    path('', views.home, name = "Home"),
    path('favsports', views.favsports, name="FavSports"),
    path('info/', views.information, name="Info")
]

MyDjango_website/Myself/mywebsite/views.py
from django.shortcuts import render
from django.http import HttpRequest, HttpResponse

def home(request:HttpRequest):
    return render(request, 'mywebsite/base.html')


def favsports(request:HttpRequest):
    context = {"sports": ["football", "Swimming", "Coding", "Camping"]
    }
    return render(request, 'mywebsite/favsport.html', context)

def information(request:HttpRequest):
    return render(request, 'mywebsite/info.html')

MyDjango_website/Myself/mywebsite/templates/mywebsite/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
 <head>
    <meta charset= "UTF-8">
    <meta http-equiv= "X-UA-Compatible" content= "IE=edge">
    <meta name= "viewport" content= "width-device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.9.1/font/bootstrap-icons.css">
    {% block title %}<title>Mohammed Website</title>{% endblock %}
    
 </head>
 <body>
 
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3" crossorigin="anonymous"></script>
    <div class="navbar navbar-expand-md bg-dark navbar-dark text-white">
        <div class="container">
            <a href="{% url 'MyWebsite:Home' %}" class= "navbar-brand">Mohammed</a>
            <button
                class= "navbar-toggler"
                type="button"
                data-bs-toggle="collapse"
                data-bs-target="#mainmenu"
            >
            <span class= "navbar-toggler-icon"></span>
        </button>
            <div class="collapse navbar-collapse" id="mainmenu">
                <ul class= "navbar-nav ms-auto">
                    <li class= "nav-item"><a href="{% url 'MyWebsite:Home' %}" class="nav-link">Home</a></li>
                    <li class= "nav-item"><a href="{% url 'MyWebsite:FavSports' %}" class= "nav-link">Favorite Sports</a></li>
                    <li class= "nav-item"><a href="{% url 'MyWebsite:Info' %}" class="nav-link">About me</a></li>
                </ul>
            </div>
        </div>
    </div>
    

    <!--Content-->
<section id= "hero" class= "bg-dark text-light text-center text-sm-start ру-5">
<div class= "container">
    <div class="d-sm-flex align-items-center justify-content-center">
        <div class= "ру-3">
            {% block content %}
            <h1 class= "display-5">Welcome to <span class="text-info">Mohammed Website</span></h1>
            <p class= "ру-1 lead" >Hello this is my website
            you are welcome anytime :D </p>
            <a href="{% url 'MyWebsite:FavSports' %}"><button class= "btn btn-info"> Get Started</button></a>
            {% endblock %}
        </div>
        <img class= "d-none d-sm-block img-fluid w-50" Src="{% static 'images/content-img.svg' %}">
   </div>
</div>
</section>

        <!--          Cards             -->
<section class="py-5">
    <div class="container">
        <div class="row text-center">

            <div class="col-sm">
                <div class="card bg-dark text-light mb-3">
                    <div class="h1 mt-3">
                        <i class= "bi bi-award-fill"></i>
                    </div>
                    <div class="card-body text-center mt-3">
                        <h4 class="card-title">Experince</h4>
                        <p class= "card-text" >We have many projects before this website. <br> Here is our last Projects & Experince </p>
                        <a href="https://twitter.com/tuwaiqacademy" class= "btn btn-info">Learn More</a>
                    </div>
                </div>
            </div>

            <div class="col-sm">
                <div class="card bg-dark text-light mb-3">
                    <div class="h1 mt-3">
                        <i class= "bi bi-code-slash"></i>
                    </div>
                    <div class="card-body text-center mt-3">
                        <h4 class="card-title">Learning Programming</h4>
                        <p class= "card-text" >Programming is so important. <br> We offer programming courses you can chick it out from here</p>
                        <a href="https://en.wikipedia.org/wiki/Computer_programming" class= "btn btn-info">Learn More</a>
                    </div>
                </div>
            </div>

            <div class="col-sm">
                <div class="card bg-dark text-light mb-3">
                    <div class="h1 mt-3">
                        <i class= "bi bi-person-lines-fill"></i>
                    </div>
                    <div class="card-body text-center mt-3">
                        <h4 class="card-title">Contact me</h4>
                        <p class= "card-text" >I'm free For any questions.<br> Working time: from 8am till 4pm </p>
                        <a href="{% url 'MyWebsite:Info' %}" class= "btn btn-info">Learn More</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
    

    
</body>
</html>

MyDjango_website/Myself/mywebsite/templates/mywebsite/favsport.html
{% extends 'mywebsite/base.html' %}
 {% block title %}<title>Favorite Sports</title>{% endblock %} 

 {% block content %}
            <h1 class= "display-5">This is my <span class="text-info">Favorite Sports:</span></h1>
            <p class= "ру-1 lead" ><ul>
                            {% for sport in sports %}
                                <li class="bg-teal-300 m-2 p-2 style="--bs-text-opacity: 1>Sport: {{ sport }}</li>
                            {% endfor %}
                                    </ul>
            </p>
            
 {% endblock %}

MyDjango_website/Myself/mywebsite/templates/mywebsite/info.html
{% extends 'mywebsite/base.html' %}
 {% block title %}<title>Info</title>{% endblock %} 

{% block content %}
            <h1 class= "display-5">My <span class="text-info">Information:</span></h1>
            <p class= "ру-1 lead" ><ul>
                                <li class=" m-2 p-2" >Name: Mohammed</li>
                                <li class=" m-2 p-2" >Number: 0530301190</li>
                                <li class=" m-2 p-2" >Email: Alharimi002@gmail.com</li>
                                </ul>
            </p>
            
 {% endblock %}