personal_website/my_app/urls.py
from django.urls import path
from django.http import HttpRequest, HttpResponse
from . import views

app_name = "my_app"


urlpatterns = [
    path('home/', views.home, name="home"),
    path('about/', views.about, name="about"),
    path('projects/', views.projects, name="projects"),
    path('contact/', views.contact, name="contact"),

    # path('today/', views.today_date, name="today_date"),
    # path('random/password', views.randomly_password, name="randomly_password"),
    #  path('favs/games/', views.favorite_games, name="favorite_games"),
]

personal_website/personal/urls.py
from django.urls import path
from . import views

app_name = "personal"

urlpatterns = [
    path("home/", views.home, name="home"),
    path("contact/", views.contact, name="contact"),
    path("my_work/", views.my_work, name="my_work"),
    path("about/", views.about, name="about"),
]

personal_website/personal_website/urls.py
from django.contrib import admin
from django.urls import path , include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('website.urls'))
]

personal_website/website/urls.py
from django.urls import path
from . import views

app_name = 'website'

urlpatterns = [
    path('',views.home, name = 'home'),
    path('colleage\\',views.colleage, name = 'colleage'),
    path('x\\',views.connect, name = 'connect'),
]

personal_website/my_app/views.py
from django.http import HttpRequest
from django.shortcuts import render
# HttpResponse
# Create your views here.

# This should display the date of today .


def home(request: HttpRequest):

    return render(request, "my_app/home.html")


def projects(request: HttpRequest):

    return render(request, "my_app/projects.html")


def contact(request: HttpRequest):

    return render(request, "my_app/contact.html")


def about(request: HttpRequest):

    return render(request, "my_app/about.html")

personal_website/personal/views.py
from django.http import HttpRequest
from django.shortcuts import render

# Create your views here.

def home(request : HttpRequest):
    return render(request,"personal/home.html")

def about(request : HttpRequest):
    return render(request,"personal/about.html")

def my_work(request : HttpRequest):
    return render(request,"personal/my_work.html")

def contact(request : HttpRequest):
    return render(request,"personal/contact.html")

personal_website/website/views.py
from django.shortcuts import render
from django.http import HttpRequest, HttpResponse

# Create your views here.


def home(request: HttpRequest): 
    context = {'msg':'Welcom'}
    return render(request, "website/base.html", context)

def colleage(request: HttpRequest): 
    return render(request, "website/colleage.html")

def connect(request: HttpRequest): 
    return render(request, "website/connect.html")

personal_website/my_app/templates/my_app/about.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% extends 'my_app/base.html' %}
    <title>{% block title %}ABOUT ME{% endblock %}</title>
</head>
<body>
    {% block content %}
    <div class="position-relative overflow-hidden p-3 p-md-5 m-md-3 text-center bg-light">
        <div class="col-md-5 p-lg-5 mx-auto my-5">
          <h2 class="  display-4 font-weight-normal"><b>ABOUT ME</b></h2>
        </div>
        <section class="about" >
            <div class="container">
                <div class="row justify-content-center">
                    <div class="col-md-10 col-lg-8">
                        <div class="">
                            <p> l'am  graduated from taibah university with computer science major,I am junior web developer I recently completed the software development bootcamp with coding dojo ,l learned web fundamental and python and mern and java. I also have web design skills.and have the ability of quick learning and I can understand new technologies very easily. I have flexible workability which helps me to work with any kind of technology.</p>
                            <p>I have a lot of skills because I have a bachelors degree in computer science. I also completed many programming courses, completed coding Dojo, l am capable of front end , back - end and full - stack roles and pick up new languages , frameworks and libraries quickly, And I have worked with a team and have the ability to manage tasks between the team I solve problems and enjoy finding solutions </p>
                           
                        </div>
                        
                        </div>
                    </div>
                </div>




                <div class="about__cta-box text-center">
                    <a href="#" class="btn btn--ghost text-dark">
                        Resume
                    </a>
                    <a href="{% url 'my_app:contact'%}" class="btn btn--full text-dark">Contact</a>
                </div>
            </div>
        </section>
      </div>
    {% endblock %}
    
</body>
</html>

personal_website/my_app/templates/my_app/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'my_app/css/footer.css'%}">
    <title>{% block title %}My amazing site{% endblock %}</title>
</head>
<body >
    <div class="container">
        <header class="d-flex flex-wrap align-items-center justify-content-center justify-content-md-between py-3 mb-4 border-bottom">
          <a href="{% url 'my_app:home'%}" class="d-flex align-items-center col-md-3 mb-2 mb-md-0 text-dark text-decoration-none">
            <h3 class="float-md-start mb-0 text-dark"><b>Bahiyyah</b></h3>
          </a>
            
          <ul class="nav col-12 col-md-auto mb-2 justify-content-center mb-md-0">
            <li><a href="{% url 'my_app:home'%}" class="nav-link px-2 link-secondary text-dark">Home</a></li>
            <li><a href="{% url 'my_app:about'%}" class="nav-link px-2 link-dark text-dark">ABOUT ME</a></li>
            <li><a href="{% url 'my_app:projects'%}" class="nav-link px-2 link-dark text-dark">My Projects</a></li>
            <li><a href="{% url 'my_app:contact'%}" class="nav-link px-2 link-dark text-dark">CONTACT ME</a></li>
          </ul>
    
        
        </header>
      </div>
        
          <main class=" text-center">
            <div class=" ">
                <div class="">
                    
                      {% block content %}
                      {% endblock %}
                 
                </div>
             </div>

          </main>
          
      <!-- footer -->
          <div class="container-fluid pb-0 mb-0 justify-content-center text-light ">
            <footer>
                <div class="row my-5 justify-content-center py-5">
                    <div class="col-11">
                        <div class="row ">
                            <div class="col-xl-8 col-md-4 col-sm-4 col-12   my-auto mx-auto a"><h3 class="text-muted mb-md-0 mb-5 bold-text">Bahiyyah.</h3></div>
                            <div class="col-xl-2 col-md-4 col-sm-4 col-12"><h6 class="mb-3 mb-lg-4 bold-text "><b>MENU</b></h6><ul class="list-unstyled"><li><a href="{% url 'my_app:home'%}" class="bold-text">Home</a></li><li><a class="bold-text" href="{% url 'my_app:about'%}">About</a></li><li><a class="bold-text" href="{% url 'my_app:projects'%}" >Projects</a></li><li><a class="bold-text" href="{% url 'my_app:contact'%}">Contact</a></li></ul></div>
                            <div class="col-xl-2 col-md-4 col-sm-4 col-12"><h6 class="mb-3 mb-lg-4 text-muted bold-text mt-sm-0 mt-5"><b>ADDRESS</b></h6><p class="mb-1">MADINAH-RIYADH</p></div>
                        </div>
                        <div class="row ">
                            <div class="col-xl-8 col-md-4 col-sm-4 col-auto  my-md-0 mt-5 order-sm-1 order-3 align-self-end"><p class="social text-muted mb-0 pb-0 bold-text"> <span  class="mx-2"><i class="fa fa-facebook" aria-hidden="true"></i></span> <span class="mx-2"><i class="fa fa-linkedin-square" aria-hidden="true"></i></span> <span class="mx-2"><i class="fa fa-twitter" aria-hidden="true"></i></span> <span class="mx-2"><i class="fa fa-instagram" aria-hidden="true"></i></span> </p><small class="rights"><span>&#174;</span>All Rights Reserved.</small></div>
                            <div class="col-xl-2 col-md-4 col-sm-4 col-auto order-1 align-self-end "><h6 class="mt-55 mt-2 text-muted bold-text"><b>Bahiyyah Aljohani</b></h6><small> <span><i class="fa fa-envelope" aria-hidden="true"></i></span> Bahiab144@gmail.com</small></div>
                        </div>
                    </div>
                </div>
            </footer>
        </div> 
          
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

        </body>
    

</html>

personal_website/my_app/templates/my_app/contact.html
{% extends 'my_app/base.html' %}
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static '/css/contact.css'%}">

    <title>{% block title %}CONTACT ME{% endblock %}</title>
</head>
<body>
    {% block content %}
    <div class="position-relative overflow-hidden p-3 p-md-5 m-md-3 text-center bg-light">
        <div class="col-md-5 p-lg-5 mx-auto my-5">
          <h2 class="  display-4 font-weight-normal"><b>CONTACT ME<b></b></h2>
        </div>
        <div class="container">
        <div class="row ">
          <div class="col-lg-7 mx-auto">
            <div class="card mt-2 mx-auto p-4 bg-light">
                <div class="card-body bg-light">
           
                <div class = "container">
                                 <form id="contact-form" role="form">
                <div class="controls">
                    <div class="row">
                        <div class="col-md-6">
                            <div class="form-group">
                                <label for="form_name">Firstname :</label>
                                <input id="form_name" type="text" name="name" class="form-control" placeholder="Please enter your firstname *" required="required" data-error="Firstname is required.">
                                
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="form-group">
                                <label for="form_lastname">Lastname :</label>
                                <input id="form_lastname" type="text" name="surname" class="form-control" placeholder="Please enter your lastname *" required="required" data-error="Lastname is required.">
                                                                </div>
                        </div>
                    </div>
                    <div class="row justify-content-center text-center">
                        <div class="col-md-6 ">
                            <div class="form-group">
                                <label for="form_email">Email :</label>
                                <input id="form_email" type="email" name="email" class="form-control" placeholder="Please enter your email *" required="required" data-error="Valid email is required.">
                                
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-12">
                            <div class="form-group">
                                <label for="form_message">Message :</label>
                                <textarea id="form_message" name="message" class="form-control" placeholder="Write your message here." rows="4" required="required" data-error="Please, leave us a message."></textarea
                                    >
                                </div>
    
                            </div>
    
    
                        <div class="col-md-12">
                            
                            <input type="submit" class="btn btn-secondary btn-send  pt-2 btn-block
                                " value="Send Message" >
                        
                    </div>
              
                    </div>
    
    
            </div>
             </form>
            </div>
                </div>
    
    
        </div>
            <!-- /.8 -->
    
        </div>
        <!-- /.row-->
    
    </div>
    </div>
    
      </div>
    {% endblock %}
    
</body>
</html>

personal_website/my_app/templates/my_app/home.html
{% extends 'my_app/base.html' %}
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static '/css/styles.css'%}">
   
    <title>{% block title %}HOME{% endblock %}</title>
</head>
<body>
    {% block content %}
  

         <br>
         <br>
        <section class="initial">
            <div class="container">
              <div class="textContent">
                <h1>Hi I'm <b>Bahiyyah</b></h1>
                <p>
                    I am junior web developer
                 
                </p>
               
              </div>
              <br>
              <br>
              <div class="images">
                <picture>
                  <source>
                  <img src="https://img.freepik.com/premium-vector/business-woman-smm-manager-programmer-sit-infographic-work-laptop-freelancer-working-web-application-development-computers-software-developers-flat-style-vector-illustration_187411-439.jpg?size=626&ext=jpg&ga=GA1.2.1208462108.1667322559" alt="">
                </picture>
              </div>
            </div>
          </section>
      
  
    {% endblock %}
    
</body>
</html>

personal_website/my_app/templates/my_app/projects.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% extends 'my_app/base.html' %}
    <title>{% block title %}HOME{% endblock %}</title>
</head>
<body>
    {% block content %}
    <br>
    <br>
    

    <div class="position-relative overflow-hidden text-center bg-light">
        <div class="">
            <h2 class="display-4 font-weight-normal pt-5"><b>My projects</b></h2>
        </div>
        <br>
        <br>

        <section class="features2 cid-ssGlc9jWjH" id="features2-6">
            <div class="container">
                <div class="mbr-section-head">
                    <div class="row header">
                        <div class="tab-content">
                                <div class="row justify-content-center">

                                    <div class=" col-sm-12 col-md-6 col-lg-4 mb-5">
                                        <div class="">
                                            <div class="">
                                                <img src="https://res.cloudinary.com/dz209s6jk/image/upload/f_auto,q_auto,w_700/Challenges/m1v21ubdjc2n75bl8p7n.jpg" alt="Project 1" class="img-fluid">
                                            </div>
                                            <div class="">
                                                <h3 class="">Room homepage</h3>
                                                <p class="">This small homepage challenge packs a big punch to test your layout skills. There's also a slider in there to add a JS layer for extra practice.</p>
                                                <div class=" text-center">
                                                    <a href="https://6317bf401c5274078df74cdb--room-homepage-fm.netlify.app/" class="btn btn--ghost text-dark">
                                                        Demo</a>
                                                    <a href="https://github.com/bahiyyah-4/Room-homepage" class="btn btn--full text-dark">
                                                        Source</a>
                                                </div>
                                            </div>
        
                                        </div>
                                    </div>
                                    <div class=" col-sm-12 col-md-6 col-lg-4 mb-5">
                                        <div class="">
                                            <div class="">
                                                <img src="https://res.cloudinary.com/dz209s6jk/image/upload/f_auto,q_auto,w_700/Challenges/rlaxdjplmeul4qe1qvh6.jpg" alt="Project 2" class=" img-fluid">
                                            </div>
                                            <div class="">
                                                <h3 class="">Intro section with dropdown navigation</h3>
                                                <p class="">create dropdown navigation menus, a common pattern on larger sites. It will also provide some nice basic layout</p>
                                                <div class=" text-center">
                                                    <a href="https://frontend-mentor-intro-section.netlify.app/ " class="btn btn--ghost text-dark">
                                                        Demo</a>
                                                    <a href="https://github.com/bahiyyah-4/Frontend-Mentor-intro-section" class="btn btn--full text-dark">
                                                        Source</a>
                                                </div>
                                            </div>
        
                                        </div>
                                    </div>
                                    <div class="col-sm-12 col-md-6 col-lg-4 mb-5">
                                        <div class="">
                                            <div class="">
                                                <img src="https://res.cloudinary.com/dz209s6jk/image/upload/f_auto,q_auto,w_700/Challenges/o4iyywkwjc31epcmsmyo.jpg" alt="Project 3" class=" img-fluid">
                                            </div>
                                            <div class="">
                                                <h3 class="">Easybank landing page</h3>
                                                <p class="">Easybank landing page layout skills</p>
                                                <div class=" text-center">
                                                    <a href="#" class="btn btn--ghost text-dark">
                                                        Demo</a>
                                                    <a href="#" class="btn btn--full text-dark">
                                                        Source</a>
                                                </div>
                                            </div>
        
                                        </div>
                                    </div>
                                    <div class="col-sm-12 col-md-6 col-lg-4 mb-5">
                                        <div class="">
                                            <div class="">
                                                <img src="https://res.cloudinary.com/dz209s6jk/image/upload/f_auto,q_auto,w_700/Challenges/i6wu7n5sthrxgfpfibvx.jpg" alt="Project 4" class=" img-fluid">
                                            </div>
                                            <div class="">
                                                <h3 class="">Single price grid component</h3>
                                                <p class=""> build out the pricing component to the designs provided</p>
                                                <div class=" text-center">
                                                    <a href="#" class="btn btn--ghost text-dark">
                                                        Demo</a>
                                                    <a href="#" class="btn btn--full text-dark">
                                                        Source</a>
                                                </div>
                                            </div>
        
                                        </div>
                                        
                                    </div>
                                    <div class="col-sm-12 col-md-6 col-lg-4 mb-5">
                                        <div class="">
                                            <div class="">
                                                <img src="https://res.cloudinary.com/dz209s6jk/image/upload/f_auto,q_auto,w_700/Challenges/ua4zwoxu3i9avrzrusre.jpg" alt="Project 4" class=" img-fluid">
                                            </div>
                                            <div class="">
                                                <h3 class="">Single price grid component</h3>
                                                <p class=""> build out the pricing component to the designs provided</p>
                                                <div class=" text-center">
                                                    <a href="https://faq-accordion-card-12.netlify.app/" class="btn btn--ghost text-dark">
                                                        Demo</a>
                                                    <a href="https://github.com/bahiyyah-4/FAQ-accordion--card" class="btn btn--full text-dark">
                                                        Source</a>
                                                </div>
                                            </div>
        
                                        </div>
                                   
                                  
            </div>
        </section></div>
        
       

    {% endblock %}
    
</body>
</html>

personal_website/website/templates/website/base.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Saud</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'style.css' %}">
    <link
    rel="stylesheet"
    href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/4.1.1/animate.min.css"
  />
  </head>
  <body>
      <header class="d-flex flex-wrap justify-content-center py-3 mb-0 border-bottom">
          <a href="/" class="d-flex align-items-center mb-0 mb-md-0 me-md-auto text-dark text-decoration-none">
            <svg class="bi me-2" width="40" height="32"><use xlink:href="#bootstrap"></use></svg>
            <span class="fs-4 text-primary">Saud</span>
          </a>
          <ul class="nav nav-pills me-5">
            <li class="nav-item"><a href="{% url 'website:home' %}" class="nav-link active" aria-current="page">Home</a></li>
            <li class="nav-item"><a href="{% url 'website:colleage' %}" class="nav-link">University</a></li>
            <li class="nav-item"><a href="{% url 'website:connect' %}" class="nav-link">Connect</a></li>
          </ul>
      </header>

    {% block main %}
      <section class="main">
          <div>
              <h2 class="animate__animated animate__fadeInDown">Hi<br><span>I'm Saud Al-Otaibi</span></h2>
              <h3 class="animate__animated animate__fadeInDown">I'm Full Stack Developer</h3> 
              <a href="#" class="mainbtn animate__animated animate__fadeInDown btn btn-primary">View My CV</a>   
              <div class="animate__animated animate__fadeInDown social-icons">

                <a href="https://www.linkedin.com/"><svg xmlns="http://www.w3.org/2000/svg" color="blue" width="24" height="24" fill="currentColor" class="bi bi-linkedin" viewBox="0 0 16 16">
                  <path d="M0 1.146C0 .513.526 0 1.175 0h13.65C15.474 0 16 .513 16 1.146v13.708c0 .633-.526 1.146-1.175 1.146H1.175C.526 16 0 15.487 0 14.854V1.146zm4.943 12.248V6.169H2.542v7.225h2.401zm-1.2-8.212c.837 0 1.358-.554 1.358-1.248-.015-.709-.52-1.248-1.342-1.248-.822 0-1.359.54-1.359 1.248 0 .694.521 1.248 1.327 1.248h.016zm4.908 8.212V9.359c0-.216.016-.432.08-.586.173-.431.568-.878 1.232-.878.869 0 1.216.662 1.216 1.634v3.865h2.401V9.25c0-2.22-1.184-3.252-2.764-3.252-1.274 0-1.845.7-2.165 1.193v.025h-.016a5.54 5.54 0 0 1 .016-.025V6.169h-2.4c.03.678 0 7.225 0 7.225h2.4z"/>
                </svg></a>

                <a href="https://www.github.com/"><svg xmlns="http://www.w3.org/2000/svg" color="blue" width="24" height="24" fill="currentColor" class="bi bi-github" viewBox="0 0 16 16">
                  <path d="M8 0C3.58 0 0 3.58 0 8c0 3.54 2.29 6.53 5.47 7.59.4.07.55-.17.55-.38 0-.19-.01-.82-.01-1.49-2.01.37-2.53-.49-2.69-.94-.09-.23-.48-.94-.82-1.13-.28-.15-.68-.52-.01-.53.63-.01 1.08.58 1.23.82.72 1.21 1.87.87 2.33.66.07-.52.28-.87.51-1.07-1.78-.2-3.64-.89-3.64-3.95 0-.87.31-1.59.82-2.15-.08-.2-.36-1.02.08-2.12 0 0 .67-.21 2.2.82.64-.18 1.32-.27 2-.27.68 0 1.36.09 2 .27 1.53-1.04 2.2-.82 2.2-.82.44 1.1.16 1.92.08 2.12.51.56.82 1.27.82 2.15 0 3.07-1.87 3.75-3.65 3.95.29.25.54.73.54 1.48 0 1.07-.01 1.93-.01 2.2 0 .21.15.46.55.38A8.012 8.012 0 0 0 16 8c0-4.42-3.58-8-8-8z"/>
                </svg></a>

                <a href="https://twitter.com/"><svg xmlns="http://www.w3.org/2000/svg" color="blue" width="24" height="24" fill="currentColor" class="bi bi-twitter" viewBox="0 0 16 16">
                  <path d="M5.026 15c6.038 0 9.341-5.003 9.341-9.334 0-.14 0-.282-.006-.422A6.685 6.685 0 0 0 16 3.542a6.658 6.658 0 0 1-1.889.518 3.301 3.301 0 0 0 1.447-1.817 6.533 6.533 0 0 1-2.087.793A3.286 3.286 0 0 0 7.875 6.03a9.325 9.325 0 0 1-6.767-3.429 3.289 3.289 0 0 0 1.018 4.382A3.323 3.323 0 0 1 .64 6.575v.045a3.288 3.288 0 0 0 2.632 3.218 3.203 3.203 0 0 1-.865.115 3.23 3.23 0 0 1-.614-.057 3.283 3.283 0 0 0 3.067 2.277A6.588 6.588 0 0 1 .78 13.58a6.32 6.32 0 0 1-.78-.045A9.344 9.344 0 0 0 5.026 15z"/>
                </svg></a>
              </div>
            </div>
          </section>
        {% endblock %}
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3" crossorigin="anonymous"></script>
</body>
</html>

personal_website/website/templates/website/colleage.html
{% load static %}

<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Colleage</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
    <link
    rel="stylesheet"
    href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/4.1.1/animate.min.css"
  />
  </head>
  <body>
      <div class="row h-100 justify-content-center align-items-center w-100 mr-0 ml-0" style="position:fixed;">
        <div class="col-12 text-center" style="color: azure; position:relative; z-index: 1;">
            <h2 class="animate__animated animate__backInLeft">King Saud University</h2>
            <h1 class="animate__animated animate__backInLeft">جامعة الملك سعود</h1>
        </div>
      </div>
        <div class="video-slide-container" style="overflow: hidden; background-position: center center;">
          <video id="bgvid" autoplay="" loop="" muted="" style="width:100%;">
          <source src="{% static 'videos/KSU_2.webm' %}" type="video/webm"></video>
        </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3" crossorigin="anonymous"></script>
  </body>
</html>

personal_website/website/templates/website/connect.html
{% extends 'website/base.html' %}
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Bootstrap demo</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
  </head>
  <body>
    {% block main %}
        <div class="mb-3 m-5">
            <label for="exampleFormControlInput1" class="form-label">Email address</label>
            <input type="email" class="form-control" id="exampleFormControlInput1" placeholder="name@gmail.com">
          </div>
          <div class="mb-3 m-5">
            <label for="exampleFormControlTextarea1" class="form-label">Text Area</label>
            <textarea class="form-control" id="exampleFormControlTextarea1" rows="3"></textarea>
          </div>
    {% endblock %}
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3" crossorigin="anonymous"></script>
  </body>
</html>