MyWebSite/MyWebSite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('website.urls'))
]

MyWebSite/website/urls.py
from django.urls import path
from .views import homePage, aboutPage, contactPage

app_name = 'website'

urlpatterns = [
    path('', homePage, name='home'),
    path('about/', aboutPage, name='about'),
    path('contact/', contactPage, name='contact'),
]

MyWebSite/website/views.py
from django.shortcuts import render
from django.http import HttpRequest

# Create your views here.
def homePage(request: HttpRequest):
    return render(request, 'website/home.html')

def aboutPage(request: HttpRequest):
    return render(request, 'website/about.html')

def contactPage(request: HttpRequest):
    return render(request, 'website/contact.html')

MyWebSite/website/templates/website/about.html
{% extends 'website/base.html' %}
{% load static %}
{% block title %}Abdulmohsen Alateeq - About{% endblock %}
{% block content %}
<div class="animate__animated animate__fadeInLeft">
    <h5 class="fs-1 mb-2 " style="text-shadow: 1px 1px black; color: blueviolet;">def <span style="color: greenyellow;">AboutMe()</span>:</h5>
    <p class="fs-4 ms-5 mb-2" style="color: blueviolet;">name:<span style="color: goldenrod;"> str</span> = <span style="color: green;">'Abdulmohsen Alateeq'</span></p>
    <p class="fs-4 ms-5 mb-2" style="color: blueviolet;">major:<span style="color: goldenrod;"> str</span> = <span style="color: green;">'Software Engineering'</span></p>
    <p class="fs-4 ms-5 mb-2" style="color: blueviolet;">Skills:<span style="color: goldenrod;"> list</span> = <span style="color: green;">[<span style="color: green;"><br />'Linux',<br />'Python',<br />'GIT',<br />'SQL'</span><br />]</span></p>
    <p class="fs-4 ms-5 mb-2" style="text-shadow: 1px 1px black; color: blueviolet;">for <span style="color: greenyellow;">contact</span> in <span style="color: greenyellow;">about</span>:</p>
    <p class="fs-4 ms-5 mb-2" style="color: blueviolet;"><span class="ms-5" style="color: greenyellow;">redirect(<a href="{% url 'website:contact' %}">CONTACT</a>)</span></p>
</div>
{% endblock %}

MyWebSite/website/templates/website/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %} Abdulmohsen Alateeq {% endblock %}</title>
    <link rel="stylesheet" href="{% static 'styles/css/normalize.css' %}">
    <link rel="stylesheet" href="{% static 'styles/css/bootstrap.css' %}">
    <link rel="stylesheet" href="{% static 'styles/css/animate.css' %}">
    <link rel="stylesheet" href="{% static 'styles/css/styles.css' %}">
</head>
<body class="overflow-hidden">
      <header class="d-flex flex-wrap justify-content-center py-3 mb-4 border-bottom container">
        <a href="{% url 'website:home' %}" class="d-flex align-items-center mb-3 mb-md-0 me-md-auto text-dark text-decoration-none animate__animated animate__lightSpeedInLeft">
          <svg width="40" height="40" viewBox="0 0 2050 2050" data-name="Layer 3" id="Layer_3" xmlns="http://www.w3.org/2000/svg"><defs><style>.cls-1{fill:#4d4d4d;}.cls-2{fill:#fff;}</style></defs><title/><path class="cls-1" d="M1009.1,1629.4a602.6,602.6,0,1,1,235.2-47.5A601,601,0,0,1,1009.1,1629.4Z"/><path class="cls-2" d="M803.5,1283a45.1,45.1,0,0,1-31.8-76.9L1202,775.8a45,45,0,0,1,63.6,63.7L835.3,1269.8A44.8,44.8,0,0,1,803.5,1283Z"/><path class="cls-2" d="M842.8,1000a45,45,0,0,1-26.9-8.9L699,904a45.1,45.1,0,0,1,0-72.2l116.9-87.1a45,45,0,0,1,53.8,72.2l-68.5,51,68.5,51a45,45,0,0,1-26.9,81.1Z"/><path class="cls-2" d="M1175.4,1314.2a45,45,0,0,1-26.9-81.1l68.4-51-68.4-51a45,45,0,1,1,53.7-72.2l117,87.1a45.1,45.1,0,0,1,0,72.2l-117,87.1A44.9,44.9,0,0,1,1175.4,1314.2Z"/></svg>
          <span class="ms-2 fs-4 navbar_title">Abdulmohsen Alateeq</span>
        </a>     
        <ul class="nav nav-pills nav-bg-dark animate__animated animate__lightSpeedInRight">
          <li class="nav-item"><a href="{% url 'website:home' %}" class="ms-3 link-secondary navbar_item" aria-current="page">Home</a></li>
          <li class="nav-item"><a href="{% url 'website:about' %}" class="ms-3 link-secondary navbar_item">About</a></li>
          <li class="nav-item"><a href="{% url 'website:contact' %}" class="ms-3 link-secondary navbar_item">Contact me</a></li>
          <li class="nav-item dropdown">
              <a class="ms-3 link-secondary navbar_item dropdown-toggle" type="button" data-bs-toggle="dropdown" aria-expanded="false">
                Useful Tools
              </a>
              <ul class="dropdown-menu">
                <li><a class="dropdown-item" href="https://cloudconvert.com/font-converter" target="_blank">Font Converter</a></li>
                <li><a class="dropdown-item" href="https://imagecompressor.com/" target="_blank">Image Compressor</a></li>
                <li><a class="dropdown-item" href="https://bennettfeely.com/clippy/" target="_blank">CSS Clip Path Maker</a></li>
              </ul>          
          </li>
        </ul>
      </header>
      <div class="container">
        {% block content %}
        {% endblock %}
      </div>
    <div class="container animate__animated animate__fadeInUp">
        <footer class="d-flex flex-wrap justify-content-between align-items-center py-3 mt-4 mb-2 border-top">
          <div class="col-md-4 d-flex align-items-center">
            <a href="/" class="mb-3 me-2 mb-md-0 text-muted text-decoration-none lh-1">
                <svg width="40" height="40" viewBox="0 0 2050 2050" data-name="Layer 3" id="Layer_3" xmlns="http://www.w3.org/2000/svg"><defs><style>.cls-1{fill:#4d4d4d;}.cls-2{fill:#fff;}</style></defs><title/><path class="cls-1" d="M1009.1,1629.4a602.6,602.6,0,1,1,235.2-47.5A601,601,0,0,1,1009.1,1629.4Z"/><path class="cls-2" d="M803.5,1283a45.1,45.1,0,0,1-31.8-76.9L1202,775.8a45,45,0,0,1,63.6,63.7L835.3,1269.8A44.8,44.8,0,0,1,803.5,1283Z"/><path class="cls-2" d="M842.8,1000a45,45,0,0,1-26.9-8.9L699,904a45.1,45.1,0,0,1,0-72.2l116.9-87.1a45,45,0,0,1,53.8,72.2l-68.5,51,68.5,51a45,45,0,0,1-26.9,81.1Z"/><path class="cls-2" d="M1175.4,1314.2a45,45,0,0,1-26.9-81.1l68.4-51-68.4-51a45,45,0,1,1,53.7-72.2l117,87.1a45.1,45.1,0,0,1,0,72.2l-117,87.1A44.9,44.9,0,0,1,1175.4,1314.2Z"/></svg>
            </a>
            <span class="mb-3 mb-md-0 text-muted">© 2022 Abdulmohsen Alateeq.</span>
          </div>
      
          <ul class="nav col-md-4 justify-content-end list-unstyled d-flex">
            <li class="ms-3"><a class="text-muted" href="https://twitter.com/mohsenalateeq" target="_blank">
                <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="currentColor" class="bi bi-twitter" viewBox="0 0 16 16">
                    <path d="M5.026 15c6.038 0 9.341-5.003 9.341-9.334 0-.14 0-.282-.006-.422A6.685 6.685 0 0 0 16 3.542a6.658 6.658 0 0 1-1.889.518 3.301 3.301 0 0 0 1.447-1.817 6.533 6.533 0 0 1-2.087.793A3.286 3.286 0 0 0 7.875 6.03a9.325 9.325 0 0 1-6.767-3.429 3.289 3.289 0 0 0 1.018 4.382A3.323 3.323 0 0 1 .64 6.575v.045a3.288 3.288 0 0 0 2.632 3.218 3.203 3.203 0 0 1-.865.115 3.23 3.23 0 0 1-.614-.057 3.283 3.283 0 0 0 3.067 2.277A6.588 6.588 0 0 1 .78 13.58a6.32 6.32 0 0 1-.78-.045A9.344 9.344 0 0 0 5.026 15z"/>
                  </svg>
            </a></li>
            <li class="ms-3"><a class="text-muted" href="https://github.com/mohsenalateeq" target="_blank">
                <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="currentColor" class="bi bi-github" viewBox="0 0 16 16">
                    <path d="M8 0C3.58 0 0 3.58 0 8c0 3.54 2.29 6.53 5.47 7.59.4.07.55-.17.55-.38 0-.19-.01-.82-.01-1.49-2.01.37-2.53-.49-2.69-.94-.09-.23-.48-.94-.82-1.13-.28-.15-.68-.52-.01-.53.63-.01 1.08.58 1.23.82.72 1.21 1.87.87 2.33.66.07-.52.28-.87.51-1.07-1.78-.2-3.64-.89-3.64-3.95 0-.87.31-1.59.82-2.15-.08-.2-.36-1.02.08-2.12 0 0 .67-.21 2.2.82.64-.18 1.32-.27 2-.27.68 0 1.36.09 2 .27 1.53-1.04 2.2-.82 2.2-.82.44 1.1.16 1.92.08 2.12.51.56.82 1.27.82 2.15 0 3.07-1.87 3.75-3.65 3.95.29.25.54.73.54 1.48 0 1.07-.01 1.93-.01 2.2 0 .21.15.46.55.38A8.012 8.012 0 0 0 16 8c0-4.42-3.58-8-8-8z"/>
                  </svg>
            </a></li>
            <li class="ms-3"><a class="text-muted" href="https://www.linkedin.com/in/mohsenalateeq/" target="_blank">
                <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="currentColor" class="bi bi-linkedin" viewBox="0 0 16 16">
                    <path d="M0 1.146C0 .513.526 0 1.175 0h13.65C15.474 0 16 .513 16 1.146v13.708c0 .633-.526 1.146-1.175 1.146H1.175C.526 16 0 15.487 0 14.854V1.146zm4.943 12.248V6.169H2.542v7.225h2.401zm-1.2-8.212c.837 0 1.358-.554 1.358-1.248-.015-.709-.52-1.248-1.342-1.248-.822 0-1.359.54-1.359 1.248 0 .694.521 1.248 1.327 1.248h.016zm4.908 8.212V9.359c0-.216.016-.432.08-.586.173-.431.568-.878 1.232-.878.869 0 1.216.662 1.216 1.634v3.865h2.401V9.25c0-2.22-1.184-3.252-2.764-3.252-1.274 0-1.845.7-2.165 1.193v.025h-.016a5.54 5.54 0 0 1 .016-.025V6.169h-2.4c.03.678 0 7.225 0 7.225h2.4z"/>
                  </svg>
            </a></li>
          </ul>
        </footer>
      </div>
    <script src="{% static 'styles/js/bootstrap.js' %}"></script>
</body>
</html>

MyWebSite/website/templates/website/contact.html
{% extends 'website/base.html' %}
{% load static %}
{% block title %}Abdulmohsen Alateeq- Contact{% endblock %}
{% block content %}
<div class="d-flex justify-content-evenly">
<div class="animate__animated animate__zoomIn" style="width: 30%;">
    <div class="fs-3 mb-3 border-bottom pb-2">Send your message</div>
    <form class="">
    <div class="input-group input-group-sm mb-3">
        <span class="input-group-text" id="inputGroup-sizing-sm">Name: </span>
        <input type="text" class="form-control" aria-label="Sizing example input" aria-describedby="inputGroup-sizing-sm">
    </div>
    <div class="input-group input-group-sm mb-3">
        <span class="input-group-text" id="inputGroup-sizing-sm">Email: </span>
        <input type="text" class="form-control" aria-label="Sizing example input" aria-describedby="inputGroup-sizing-sm">
    </div>
    <div class="input-group input-group-sm">
        <span class="input-group-text w-100" id="inputGroup-sizing-sm">Message: </span>
        <input type="text" class="form-control w-100" style="height: 250px; margin-top: -3px; margin-left: 1px;" aria-label="Sizing example input" aria-describedby="inputGroup-sizing-sm">
    </div>
    <div class="input-group input-group-sm mb-3">
        <button class="btn btn-outline-secondary w-100" type="button"  style="margin-top: -1px; margin-left: 1px;" id="inputGroupFileAddon04">Send Message</button>      
    </div>
    </form>
</div>
<div class="animate__animated animate__zoomIn" style="width: 30%;">
    <div class="fs-3 mb-3 border-bottom pb-2">Address</div>
    <div class="fs-5 mb-2 pb-1 text-secondary" style="border-bottom: 1px dashed silver;">Kingdom of Saudi Arabia</div>
    <div class="fs-5 mb-2 pb-1 text-secondary" style="border-bottom: 1px dashed silver;">Riyadh, Ishbiliyah</div>
    <div class="d-inline-flex fs-5 mb-3 pb-1 text-secondary" style="border-bottom: 1px dashed silver;">13325, 4624</div>
    <div class="border rounded-3 w-100" style="height: 55%;" id="map"></div>
</div>
</div>
<script>
    // Initialize and add the map
function initMap() {
  // The location of Uluru
  const uluru = { lat: 24.793370628248915, lng: 46.79215455046611 };
  // The map, centered at Uluru
  const map = new google.maps.Map(document.getElementById("map"), {
    zoom: 15,
    center: uluru,
  });
  // The marker, positioned at Uluru
  const marker = new google.maps.Marker({
    position: uluru,
    map: map,
  });
}

window.initMap = initMap;
</script>
<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyAPoMDkxoYYG0QoLei3zi4clSbU4dFkNNQ&callback=initMap&v=weekly" defer></script>
{% endblock %}

MyWebSite/website/templates/website/home.html
{% extends 'website/base.html' %}
{% load static %}
{% block title %}Abdulmohsen Alateeq{% endblock %}
{% block content %}
    <div id="carouselExampleCaptions" class="carousel slide animate__animated animate__zoomIn" data-bs-ride="false">
        <div class="carousel-inner">
          <div class="carousel-item active">
            <video class="w-100 rounded-5 mx-auto d-block video_item" autoplay muted loop>
                <source src="{% static 'videos/landing.mp4' %}" type="video/mp4">
                Your browser does not support the video tag.
            </video> 
            <div class="carousel-caption d-none d-md-block mt-5 video_caption">
              <h5 class="fs-1 mb-3 home_caption" style="text-shadow: 2px 1px black;">Hi, I'm Abdulmohsen Alateeq...</h5>
              <p class="fs-4 ms-5 mt-5" style="text-shadow: 2px 1px black;">💻  Interested in Web Development!</p>
              <p class="fs-4 ms-5" style="text-shadow: 2px 1px black;">📰  I'm a <span style="color: greenyellow;">Python</span> back-end developer at <a href="https://imlink.network/" target="_blank" rel="noopener noreferrer">Link App</a> and <a href="https://bootcamp.sa/" target="_blank" rel="noopener noreferrer">Tuwaiq Academy</a>.</p>
              <p class="fs-4 ms-5" style="text-shadow: 2px 1px black;">💞️  So exciting to collaborate on web projects.</p>
              <p class="fs-4 ms-5" style="text-shadow: 2px 1px black;">📫  Feel free to reach me at <a href="{% url 'website:contact' %}">CONTACT</a> or Email: <a href="mailto:mohsenalateeq@gmail.com">mohsenalateeq@gmail.com</a>.</p>
            </div>
          </div>
        </div>
      </div> 
{% endblock %}